export default {
    logIn: 1,
    home: 2,
    register: 3,
    post: 4,
    chatBox: 5,
    info: 6,
    detail: 7,
    exchange: 8,
    messenger: 9,
    stock: 10,
    addStock: 11,
    stockDetail: 12,
    myStock: 13,
    waitting: 14,
    myShop: 15,
    bought: 16,
    other: 17,
}